#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Set up beatstash with a new or existing Navidrome server.\n' "$DIM"
  printf '  You will need your Telegram credentials and a Navidrome admin account.\n'
  printf '  The installer saves your settings and starts the services with Docker.\n'
  printf '  Press Ctrl-C to stop. Run it again in the same directory to continue.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
RELEASE_TAG='__BEATSTASH_INSTALLER_RELEASE_TAG__'
REPOSITORY='__BEATSTASH_INSTALLER_REPOSITORY__'
[[ "$REPOSITORY" == __* ]] && REPOSITORY='lubaskinc0de/beatstash'

fail() { printf '%sError: %s%s\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# Double-quoted Compose values escape backslashes, quotes, and interpolation.
encode_env() {
  local value="$1"
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || fail 'Values must fit on one line.'
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  value=${value//\$/\$\$}
  printf '"%s"' "$value"
}
decode_env() {
  local value="$1" decoded='' char next index
  if [[ "$value" == \"*\" ]]; then
    value=${value:1:${#value}-2}
    for ((index=0; index<${#value}; index++)); do
      char=${value:index:1}
      next=${value:index+1:1}
      if [[ "$char" == \\ && ( "$next" == \\ || "$next" == \" ) ]]; then
        decoded+="$next"
        index=$((index+1))
      elif [[ "$char" == '$' && "$next" == '$' ]]; then
        decoded+='$'
        index=$((index+1))
      else
        decoded+="$char"
      fi
    done
    printf '%s' "$decoded"
  elif [[ "$value" == \'*\' ]]; then
    # Read values saved by earlier installer versions without evaluating them.
    value=${value:1:${#value}-2}
    value=${value//\\\'/\'}
    printf '%s' "$value"
  else
    printf '%s' "$value"
  fi
}
get_value() { decode_env "$(_existing "$1" || true)"; }
save_value() { write_env "$1" "$(encode_env "$2")"; chmod 600 "$ENV_FILE"; }
prompt_value() {
  local name="$1" prompt="$2" default="${3:-}" secret="${4:-}" previous raw
  previous=$(_existing "$name" || true)
  if [[ "$secret" == secret ]]; then ask_secret "$name" "$prompt"; else ask "$name" "$prompt"; fi
  raw=${!name}
  [[ -n "$previous" && "$raw" == "$previous" ]] && raw=$(decode_env "$raw")
  [[ -n "$raw" ]] || raw="$default"
  printf -v "$name" '%s' "$raw"
  save_value "$name" "$raw"
}
required_value() {
  local name="$1" prompt="$2" pattern="$3" secret="${4:-}"
  while true; do
    prompt_value "$name" "$prompt" '' "$secret"
    [[ "${!name}" =~ $pattern ]] && return 0
    warn 'Please enter a value in the requested format.'
  done
}
state_value() {
  local previous="$ENV_FILE" value
  ENV_FILE="$STATE_FILE"; value=$(get_value "$1"); ENV_FILE="$previous"
  printf '%s' "$value"
}
save_state() {
  local previous="$ENV_FILE"
  ENV_FILE="$STATE_FILE"; save_value "$1" "$2"; ENV_FILE="$previous"
}
toml_string() { jq -Rn --arg value "$1" '$value'; }
set_config() {
  local section="$1" key="$2" value="$3" tmp
  tmp=$(mktemp "${CONFIG_FILE}.XXXXXX")
  CONFIG_SECTION="$section" CONFIG_KEY="$key" CONFIG_VALUE="$value" awk '
    BEGIN { section=""; found=0 }
    /^\[/ { section=$0; gsub(/^\[|\]$/, "", section) }
    section == ENVIRON["CONFIG_SECTION"] && $0 ~ "^" ENVIRON["CONFIG_KEY"] "[[:space:]]*=" {
      print ENVIRON["CONFIG_KEY"] " = " ENVIRON["CONFIG_VALUE"]; found++; next
    }
    { print }
    END { if (found != 1) exit 1 }
  ' "$CONFIG_FILE" > "$tmp" || { rm -f "$tmp"; fail "Cannot update $key in config.toml."; }
  chmod 600 "$tmp"; mv "$tmp" "$CONFIG_FILE"
}
compose() { env -u BOT_TOKEN -u SECRET_KEY -u NAVIDROME_PASSWORD -u TELEGRAM_API_ID -u TELEGRAM_API_HASH -u POSTGRES_PASSWORD -u BEATSTASH_VERSION docker compose --project-directory "$DEPLOY_DIR" -f "$DEPLOY_DIR/compose.yml" --env-file "$DEPLOY_DIR/.env" "$@"; }
check_project() {
  local id owner
  while read -r id; do
    [[ -n "$id" ]] || continue
    owner=$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project.working_dir"}}' "$id")
    [[ "$owner" == "$DEPLOY_DIR" ]] || fail "Another beatstash stack already runs from $owner. Run its installer there."
  done < <(docker ps -aq --filter label=com.docker.compose.project=beatstash)
}
ensure_secret() {
  local name="$1" format="$2" value
  value=$(get_value "$name")
  if [[ -z "$value" ]]; then
    if docker volume inspect beatstash_postgres_data >/dev/null 2>&1; then
      fail "Existing database found. Restore its original .env before generating $name."
    fi
    value=$(openssl rand "$format" 32)
    save_value "$name" "$value"
  fi
}
verify_archive() {
  local archive="$1" manifest
  manifest=$(tar -tzf "$archive" | LC_ALL=C sort)
  [[ "$manifest" == $'LICENSE\ndeploy/.env.example\ndeploy/compose.yml\ndeploy/config.example.toml' ]] || fail 'Unexpected files in the deployment archive.'
  # Reject links and special files before extracting.
  tar -tvzf "$archive" | awk 'substr($0,1,1)!="-" {exit 1}' || fail 'Archive must contain regular files only.'
}
download_release() {
  local base="https://github.com/$REPOSITORY/releases/download/$RELEASE_TAG" filename="beatstash-$RELEASE_TAG-deploy.tar.gz" checksum
  curl --fail --silent --show-error --location "$base/$filename" -o "$SCRATCH/$filename"
  curl --fail --silent --show-error --location "$base/$filename.sha256" -o "$SCRATCH/checksum"
  checksum=$(awk 'NR==1 {print $1}' "$SCRATCH/checksum")
  [[ "$checksum" =~ ^[a-f0-9]{64}$ ]] || fail 'Invalid release checksum.'
  printf '%s  %s\n' "$checksum" "$SCRATCH/$filename" | sha256sum -c -
  verify_archive "$SCRATCH/$filename"
  tar -xzf "$SCRATCH/$filename" -C "$SCRATCH" --no-same-owner
  local file
  for file in compose.yml .env.example config.example.toml; do
    [[ -f "$DEPLOY_DIR/$file" ]] || cp "$SCRATCH/deploy/$file" "$DEPLOY_DIR/$file"
  done
  [[ -f "$ENV_FILE" ]] || cp "$DEPLOY_DIR/.env.example" "$ENV_FILE"
  [[ -f "$CONFIG_FILE" ]] || cp "$DEPLOY_DIR/config.example.toml" "$CONFIG_FILE"
  chmod 600 "$ENV_FILE" "$CONFIG_FILE"
}

main() {
  if [[ "${1:-}" == --help ]]; then
    printf 'Usage: bash install.sh\nInteractive Docker Compose setup for new or existing Navidrome servers.\n'
    return
  fi
  [[ $# == 0 ]] || fail 'Use --help for usage.'
  [[ ${BASH_VERSINFO[0]} -ge 4 ]] || fail 'Bash 4 or later is required.'
  [[ -t 0 ]] || fail 'Run bash install.sh from an interactive terminal.'
  umask 077
  local tool
  for tool in curl jq openssl tar sha256sum awk docker; do command -v "$tool" >/dev/null || fail "Install $tool first."; done
  docker compose version >/dev/null || fail 'Install the Docker Compose plugin first.'
  docker info >/dev/null 2>&1 || fail 'Docker must be running and accessible to your user.'
  SCRATCH=$(mktemp -d)
  trap 'rm -rf "$SCRATCH"' EXIT
  banner 'Install beatstash'

  stage 'Choose your installation'
  say 'Run this installer on the server that will store your music.'
  ENV_FILE=/dev/null
  ask INSTALL_DIR 'Installation directory [./beatstash]:'
  INSTALL_DIR=${INSTALL_DIR:-./beatstash}
  (umask 022; mkdir -p "$INSTALL_DIR/deploy")
  DEPLOY_DIR=$(cd "$INSTALL_DIR/deploy" && pwd -P)
  STATE_FILE="$DEPLOY_DIR/.installer.env"
  CONFIG_FILE="$DEPLOY_DIR/config.toml"
  ENV_FILE="$STATE_FILE"
  required_value INSTALL_MODE 'Navidrome: new or existing [type new/existing]:' '^(new|existing)$'
  local old_mode
  old_mode=$(state_value SAVED_MODE)
  [[ -z "$old_mode" || "$old_mode" == "$INSTALL_MODE" ]] || fail 'Use another directory to change installation mode.'
  save_state SAVED_MODE "$INSTALL_MODE"
  ENV_FILE="$DEPLOY_DIR/.env"
  check_project
  local saved_version
  saved_version=$(get_value BEATSTASH_VERSION)
  if [[ -n "$saved_version" ]]; then
    RELEASE_TAG="v$saved_version"
  elif [[ "$RELEASE_TAG" == __* ]]; then
    RELEASE_TAG=$(curl --fail --silent --show-error --location "https://api.github.com/repos/$REPOSITORY/releases/latest" | jq -er '.tag_name')
  fi
  [[ "$RELEASE_TAG" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z.-]+)?$ ]] || fail 'Invalid release version.'
  say "Installing $RELEASE_TAG into $DEPLOY_DIR"
  download_release
  mkdir -p "$DEPLOY_DIR/music/shared" "$DEPLOY_DIR/music/users" "$DEPLOY_DIR/data/navidrome"
  chmod 755 "$DEPLOY_DIR/music" "$DEPLOY_DIR/music/shared" "$DEPLOY_DIR/music/users"
  if [[ "$INSTALL_MODE" == existing ]]; then
    local tmp
    tmp=$(mktemp "$DEPLOY_DIR/compose.yml.XXXXXX")
    awk '/^  navidrome:/ {skip=1; next} skip && /^[^ ]/ {skip=0} !skip {print}' "$DEPLOY_DIR/compose.yml" > "$tmp"
    mv "$tmp" "$DEPLOY_DIR/compose.yml"
  fi

  stage 'Create your Telegram bot'
  open_url 'https://t.me/BotFather'
  step 'Send /newbot to BotFather, choose a name and username, and copy its token.'
  required_value BOT_TOKEN 'Bot token:' '^[0-9]+:[A-Za-z0-9_-]+$' secret
  step 'Send /setinline, select your bot, and enter a search prompt such as Search music.'
  step 'Send /setinlinefeedback, select your bot, and choose 100%.'
  pause 'Press Enter once inline mode and feedback are enabled.'

  stage 'Choose the bot administrator'
  open_url 'https://t.me/Get_myidrobot'
  step 'Start Get_myidrobot and copy your numeric Telegram user ID.'
  ENV_FILE="$STATE_FILE"
  required_value ADMIN_ID 'Your Telegram user ID:' '^[1-9][0-9]*$'
  prompt_value ADMIN_CONTACT 'Contact shown to new visitors [optional, e.g. @your_name]:'
  ENV_FILE="$DEPLOY_DIR/.env"
  set_config '' admins "[\"telegram:$ADMIN_ID\"]"
  set_config '' admin_contact "$(toml_string "$ADMIN_CONTACT")"

  stage 'Set up the local Telegram API'
  open_url 'https://my.telegram.org/apps'
  step 'Sign in with your Telegram account. In API development tools, create an application if needed.'
  step 'Copy its api_id and api_hash. These belong to your Telegram application, separately from the bot token.'
  required_value TELEGRAM_API_ID 'API ID:' '^[1-9][0-9]*$'
  required_value TELEGRAM_API_HASH 'API hash:' '^[a-fA-F0-9]{32}$' secret
  ensure_secret SECRET_KEY -base64
  ensure_secret POSTGRES_PASSWORD -hex
  set_config telegram bot_api_url '"http://telegram-bot-api:8081"'
  set_config library music_dir '"/music"'

  stage 'Connect Navidrome'
  ENV_FILE="$STATE_FILE"
  prompt_value NAVIDROME_USER 'Navidrome administrator username [admin]:' admin
  if [[ "$INSTALL_MODE" == new ]]; then
    NAVIDROME_URL='http://navidrome:4533'; NAVIDROME_MUSIC_DIR='/music'
    say 'Navidrome will listen on this server at http://localhost:4533.'
    say 'For a remote server, open an SSH tunnel on your computer: ssh -L 4533:localhost:4533 user@your-server'
  else
    required_value NAVIDROME_URL 'Navidrome URL reachable from the bot (e.g. https://music.example.com):' '^https?://[^[:space:]"\\]+$'
    [[ "$NAVIDROME_URL" != *://localhost* && "$NAVIDROME_URL" != *://127.0.0.1* ]] || fail 'localhost inside the bot points to the bot itself. Use your Navidrome server address.'
    prompt_value NAVIDROME_MUSIC_DIR 'New music folder as Navidrome sees it [/beatstash-music]:' /beatstash-music
    [[ "$NAVIDROME_MUSIC_DIR" == /* && "$NAVIDROME_MUSIC_DIR" != / ]] || fail 'Use an absolute directory path for new music.'
    say "Your existing music stays in its current folders. Add this read-only mount to your Navidrome Compose service:"
    say "  - $DEPLOY_DIR/music:$NAVIDROME_MUSIC_DIR:ro"
    say 'Keep the existing music mounts. Apply the change to your Navidrome stack before continuing.'
    say 'For a native Navidrome install, use the host music path instead and allow Navidrome to read it.'
    pause 'Press Enter once Navidrome can read the new music folder.'
  fi
  prompt_value NAVIDROME_PUBLIC_URL 'Public listening URL [optional, e.g. https://music.example.com]:'
  ENV_FILE="$DEPLOY_DIR/.env"
  required_value NAVIDROME_PASSWORD 'Navidrome administrator password:' '.+' secret
  set_config navidrome user "$(toml_string "$NAVIDROME_USER")"
  set_config navidrome url "$(toml_string "$NAVIDROME_URL")"
  set_config navidrome public_url "$(toml_string "$NAVIDROME_PUBLIC_URL")"
  set_config library navidrome_music_dir "$(toml_string "$NAVIDROME_MUSIC_DIR")"
  if [[ "$INSTALL_MODE" == new ]]; then
    confirm 'Start Navidrome so you can create its administrator account' || fail 'Settings saved. Rerun the installer when ready.'
    compose up -d navidrome
    open_url 'http://localhost:4533'
    step 'Create the first Navidrome account using the username and password you just entered.'
    say 'If an account already exists, use that administrator account instead.'
    pause 'Press Enter once you can sign in to Navidrome.'
  fi

  stage 'Start beatstash'
  compose config --quiet
  say 'This starts PostgreSQL, the local Telegram API, and your bot.'
  confirm 'Download the images and start this stack' || fail 'Settings saved. To start later, rerun this installer.'
  local token_hash response logout_hash
  token_hash=$(printf '%s' "$BOT_TOKEN" | sha256sum | awk '{print $1}')
  logout_hash=$(state_value LOGOUT_TOKEN_HASH)
  if [[ "$logout_hash" != "$token_hash" ]]; then
    say 'Before using the local Telegram API, this bot must leave the cloud API.'
    confirm 'All other instances of this Telegram bot are stopped; switch it to the local API' || fail 'Settings saved. Stop the other instance before continuing.'
    # Keep the token out of process arguments and error output.
    response=$(printf 'url = "https://api.telegram.org/bot%s/logOut"\n' "$BOT_TOKEN" | curl --config - --silent --request POST) || fail 'Telegram logout failed. Check your connection and try again.'
    [[ $(printf '%s' "$response" | jq -r '.ok') == true ]] || fail 'Telegram did not accept logout. Stop the other bot instance and try again later.'
    save_state LOGOUT_TOKEN_HASH "$token_hash"
  fi
  compose pull
  compose up -d
  compose ps
  local key
  local -a runtime_keys=()
  for key in "${WRITTEN_ENV[@]}"; do
    case "$key" in
      BOT_TOKEN|SECRET_KEY|NAVIDROME_PASSWORD|TELEGRAM_API_ID|TELEGRAM_API_HASH|POSTGRES_PASSWORD) runtime_keys+=("$key") ;;
    esac
  done
  WRITTEN_ENV=("${runtime_keys[@]}")
  finish
  say "Configuration: $CONFIG_FILE"
  say "To manage this stack: cd '$DEPLOY_DIR' && docker compose ps"
  say 'Open your bot in Telegram and send /start. Link your Navidrome account in Settings.'
  say 'For HTTPS setup: https://lubaskinc0de.github.io/beatstash/administration/https/'
}

main "$@"
